import { useState } from 'react'
import { DateTime } from 'luxon'
import { Button } from '@fluentui/react-components'
import { Add20Regular, ArrowSync20Regular, ArrowUpload20Regular, ChevronLeft20Regular, ChevronRight20Regular } from '@fluentui/react-icons'
import { useModel, uid } from './model'
import { SectionTitle, Panel, Field, TextField, SaveButton, readForm, str } from './components'
import { expandManual, startOfWeek } from '../../shared/calendar'
import { visibleCalendarEvents } from '../../shared/domain'
import type { CalendarEvent, IcsPreview, Semester } from '../../shared/types'

export function CalendarView() {
  const { state, run, reload, mutate } = useModel()
  const [semesterId, setSemesterId] = useState(''), [importing, setImporting] = useState(false), [manual, setManual] = useState(false), [selected, setSelected] = useState<CalendarEvent | null>(null)
  const semester = state.semesters.find(s => s.id === semesterId) || state.semesters.filter(s => !s.archived).at(-1)
  const zone = semester?.timezone || state.settings.timezone
  const currentWeek = () => startOfWeek(DateTime.now().setZone(zone))
  const [week, setWeek] = useState(currentWeek)
  const courses = state.courses.filter(c => c.semesterId === semester?.id)
  const sources = state.sources.filter(s => s.semesterId === semester?.id)
  const days = Array.from({ length: 7 }, (_, i) => startOfWeek(week).plus({ days: i }))
  const events = visibleCalendarEvents(state.events, courses, sources, state.semesters)
  return <>
    <SectionTitle title="周课表" subtitle="留出每一周的节奏，也为变化留一点空间。" actions={<><Button icon={<ArrowSync20Regular />} onClick={() => void run(async () => { await window.workstation.syncCalendars(); await reload() }, '课表刷新完成，请查看来源状态')}>刷新订阅</Button><Button icon={<ArrowUpload20Regular />} disabled={!semester} onClick={() => setImporting(true)}>导入 ICS</Button><Button appearance="primary" icon={<Add20Regular />} disabled={!courses.length} onClick={() => setManual(true)}>手动安排</Button></>} />
    <div className="calendar-toolbar"><select aria-label="课表学期" value={semester?.id || ''} onChange={e => setSemesterId(e.target.value)}>{!state.semesters.length && <option value="">请先创建学期</option>}{state.semesters.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</select><Button aria-label="上一周" icon={<ChevronLeft20Regular />} onClick={() => setWeek(w => w.minus({ weeks: 1 }))} /><Button onClick={() => setWeek(currentWeek())}>本周</Button><Button aria-label="下一周" icon={<ChevronRight20Regular />} onClick={() => setWeek(w => w.plus({ weeks: 1 }))} /><strong>{week.toFormat('yyyy年M月d日')} — {week.plus({ days: 6 }).toFormat('M月d日')}</strong><span className="muted">{zone}</span></div>
    <section className="week-grid surface">{days.map(day => { const date = day.toISODate(); const dayEvents = events.filter(e => { const start = DateTime.fromISO(e.start, { zone }).setZone(zone), end = DateTime.fromISO(e.end, { zone }).setZone(zone); return start.startOf('day') <= day.endOf('day').setZone(zone, { keepLocalTime: true }) && end > day.startOf('day').setZone(zone, { keepLocalTime: true }) }).sort((a, b) => a.start.localeCompare(b.start)); const today = date === DateTime.now().setZone(zone).toISODate(); return <div className="week-day" key={date}><div className={`week-day-heading ${today ? 'today' : ''}`}><span>{day.setLocale('zh-CN').toFormat('ccc')}</span><strong>{day.day}</strong></div><div className="day-events">{dayEvents.map(event => { const course = courses.find(c => c.id === event.courseId); return <button key={event.id} className="calendar-event" style={{ borderLeftColor: course?.color || '#8a8886' }} onClick={() => setSelected(event)}><span>{event.allDay ? '全天' : `${DateTime.fromISO(event.start).setZone(zone).toFormat('HH:mm')}–${DateTime.fromISO(event.end).setZone(zone).toFormat('HH:mm')}`}</span><strong>{event.title}</strong><small>{course?.code || course?.name || '未关联课程'}</small>{event.location && <small>{event.location}</small>}</button>})}{!dayEvents.length && <span className="no-events">—</span>}</div></div> })}</section>
    <section className="calendar-sources"><div className="section-header"><h3>课表来源</h3><span className="muted">订阅每小时刷新 · 同步失败时保留上次安排</span></div>{sources.length ? sources.map(s => <div className="source-row surface" key={s.id}><div><strong>{s.name}</strong><small>{s.url ? '日历订阅' : '本地导入'} · {s.lastSync ? `上次同步 ${DateTime.fromISO(s.lastSync).setZone(zone).toFormat('M/d HH:mm')}` : '尚未同步'}</small>{s.error && <small className="warning-text">{s.error}</small>}</div><Button onClick={() => setImporting(true)}>重新导入 / 映射</Button>{s.url && <Button onClick={() => void mutate(w => { w.sources.find(x => x.id === s.id)!.url = '' })}>停用自动订阅</Button>}</div>) : <p className="muted">尚未添加来源。支持 ICS 文件和 HTTPS 日历订阅；普通学校网页可保存在课程主页。</p>}</section>
    {importing && semester && <IcsImport semesterId={semester.id} close={() => setImporting(false)} />}
    {manual && semester && <ManualSchedule semesterId={semester.id} close={() => setManual(false)} />}
    {selected && <Panel title="课程安排" close={() => setSelected(null)}><form onSubmit={async e => { const f = readForm(e); if (await mutate(s => { const target = s.events.find(x => x.id === selected.id); if (!target) throw new Error('此安排已被课表刷新替换，请重新打开'); target.courseId = str(f, 'course'); if (!target.sourceId) { target.title = str(f, 'title'); target.start = DateTime.fromISO(str(f, 'start'), { zone }).toISO()!; target.end = DateTime.fromISO(str(f, 'end'), { zone }).toISO()!; target.location = str(f, 'location') } })) setSelected(null) }}><Field label="关联课程"><select name="course" defaultValue={selected.courseId}>{selected.sourceId && <option value="">未关联</option>}{courses.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></Field>{selected.sourceId ? <><h3>{selected.title}</h3><p>{selected.start} — {selected.end}</p><p>{selected.location}</p><p className="info-note">导入安排的时间由来源维护，刷新时会更新。可在此调整课程关联。</p></> : <><TextField label="标题" name="title" value={selected.title} required /><TextField label="开始" name="start" type="datetime-local" value={DateTime.fromISO(selected.start).setZone(zone).toFormat("yyyy-MM-dd'T'HH:mm")} required /><TextField label="结束" name="end" type="datetime-local" value={DateTime.fromISO(selected.end).setZone(zone).toFormat("yyyy-MM-dd'T'HH:mm")} required /><TextField label="地点" name="location" value={selected.location} /></>}<div className="form-actions">{!selected.sourceId && <Button onClick={async () => { if (await mutate(s => { s.events = s.events.filter(x => x.id !== selected.id) })) setSelected(null) }}>删除此次安排</Button>}<SaveButton /></div></form></Panel>}
  </>
}
export function IcsImport({ semesterId, close, draftSemester }: { semesterId: string; close(): void; draftSemester?: Semester }) {
  const { state, run, mutate, busy } = useModel()
  const [sourceId, setSourceId] = useState(uid()), [sourceName, setName] = useState('课表导入'), [url, setUrl] = useState(''), [preview, setPreview] = useState<IcsPreview | null>(null), [mapping, setMapping] = useState<Record<string, string>>({})
  const sources = state.sources.filter(s => s.semesterId === semesterId), courses = state.courses.filter(c => c.semesterId === semesterId)
  return <Panel title="导入课表" close={close} wide><Field label="导入到来源"><select value={sources.some(s => s.id === sourceId) ? sourceId : 'new'} onChange={e => { const source = sources.find(s => s.id === e.target.value); setSourceId(source?.id || uid()); setName(source?.name || '课表导入'); setUrl(source?.url || ''); setPreview(null) }}><option value="new">建立新来源</option>{sources.map(s => <option key={s.id} value={s.id}>{s.name}（更新原有安排）</option>)}</select></Field><Field label="来源名称"><input value={sourceName} onChange={e => setName(e.target.value)} /></Field><Field label="日历订阅链接（留空则选择 ICS 文件）"><input value={url} placeholder="https://…/calendar.ics" onChange={e => { setUrl(e.target.value); setPreview(null) }} /></Field><Button disabled={busy} onClick={() => void run(async () => { const result = await window.workstation.previewIcs({ url: url || undefined, semesterId, sourceId, semester: draftSemester }); if (result) { setPreview(result); const next: Record<string, string> = {}; for (const event of result.events) next[event.uid] = state.events.find(e => e.sourceId === sourceId && e.uid === event.uid)?.courseId || ''; setMapping(next) } })}>{busy ? '正在解析…' : url ? '获取订阅并预览' : '选择 ICS 文件并预览'}</Button>
    {preview && <><div className="section-header"><h3>预览 · {preview.events.length} 个安排</h3></div>{preview.warnings.map(w => <p className="info-note" key={w}>{w}</p>)}<div className="import-preview">{[...new Map(preview.events.map(e => [e.uid, e])).values()].map(e => <Field key={e.uid} label={`${e.title} · ${preview.events.filter(x => x.uid === e.uid).length} 次`}><select value={mapping[e.uid] || ''} onChange={event => setMapping(m => ({ ...m, [e.uid]: event.target.value }))}><option value="">暂不关联课程</option>{courses.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></Field>)}</div><p className="muted">确认后替换此来源的安排，其他来源与手动课表保留。</p></>}
    <div className="form-actions"><Button onClick={close}>取消</Button><Button appearance="primary" disabled={!preview || !sourceName.trim() || busy} onClick={async () => { if (preview && await mutate(s => { const source = { id: sourceId, name: sourceName.trim(), url: url.replace(/^webcal:/, 'https:'), semesterId, lastSync: new Date().toISOString(), error: '' }; s.sources = [...s.sources.filter(x => x.id !== sourceId), source]; s.events = [...s.events.filter(e => e.sourceId !== sourceId), ...preview.events.map(e => ({ ...e, courseId: mapping[e.uid] || '' }))] })) close() }}>确认导入</Button></div>
  </Panel>
}

export function ManualSchedule({ semesterId, close }: { semesterId: string; close(): void }) {
  const { state, run, mutate } = useModel()
  const semester = state.semesters.find(s => s.id === semesterId)!
  const zone = semester.timezone
  const courses = state.courses.filter(c => c.semesterId === semesterId)
  return <Panel title="手动安排课程" close={() => close()} wide><form onSubmit={async e => { const f = readForm(e); const result = await run(async () => expandManual({ courseId: str(f, 'course'), title: str(f, 'title'), from: str(f, 'from'), to: str(f, 'to'), weekday: Number(str(f, 'weekday')), time: str(f, 'time'), endTime: str(f, 'endTime'), weeks: str(f, 'weeks'), specific: str(f, 'specific'), exceptions: str(f, 'exceptions'), timezone: zone, weekStart: semester.weekStart || semester.start, location: str(f, 'location') })); if (result && result.length && await mutate(s => { s.events.push(...result) })) close() }}><Field label="课程"><select name="course">{courses.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><TextField label="标题 / 类型" name="title" required placeholder="例如 Lecture / Tutorial / Lab" /><div className="form-grid"><Field label="星期"><select name="weekday">{['一', '二', '三', '四', '五', '六', '日'].map((d, i) => <option key={d} value={i + 1}>星期{d}</option>)}</select></Field><Field label="重复规则"><select name="weeks"><option value="every">每周</option><option value="odd">单周</option><option value="even">双周</option><option value="specific">指定教学周</option></select></Field><TextField label="开始时间" name="time" type="time" value="09:00" required /><TextField label="结束时间" name="endTime" type="time" value="10:00" required /><TextField label="生效开始日期" name="from" type="date" value={semester.start} required /><TextField label="生效结束日期" name="to" type="date" value={semester.end} required /></div><TextField label="指定周次" name="specific" placeholder="例如 1,3,5" /><TextField label="例外停课日期" name="exceptions" placeholder="例如 2026-09-21,2026-10-05" /><TextField label="地点 / 线上链接" name="location" /><p className="muted">周次以教学第一周起点计算。学期假期说明：{semester.holidays || '无'}；需要排除的具体日期请填入例外日期。</p><div className="form-actions"><SaveButton label="生成课程安排" /></div></form></Panel>
}
