import { useEffect, useState } from 'react'
import { Button, Badge } from '@fluentui/react-components'
import { ArrowDownload20Regular, ArrowUpload20Regular, PlugConnected20Regular, ShieldCheckmark20Regular } from '@fluentui/react-icons'
import { SectionTitle, Field, TextField, SaveButton, readForm, str } from './components'
import { useModel } from './model'
import type { Connection } from '../../shared/types'
export function SettingsView() {
  const { state, mutate, run, reload, busy } = useModel()
  const [connection, setConnection] = useState<Connection | null>(null)
  useEffect(() => { void run(async () => setConnection(await window.workstation.connection())) }, [])
  return <>
    <SectionTitle title="设置" subtitle="你的工作台，按你的方式运行。" />
    <div className="settings-grid"><section className="surface settings-section"><h2>外观与桌面</h2><p className="muted">Windows Fluent 主题 · 后续主题可带来不同排版</p><Field label="外观模式"><select value={state.settings.appearance} onChange={e => void mutate(s => { s.settings.appearance = e.target.value as typeof s.settings.appearance })}><option value="system">跟随系统</option><option value="light">浅色</option><option value="dark">深色</option></select></Field><div className="theme-previews"><button className={`theme-preview light ${state.settings.appearance === 'light' ? 'chosen' : ''}`} onClick={() => void mutate(s => { s.settings.appearance = 'light' })}><div><i /><span><b /><b /><b /></span></div><strong>浅色</strong></button><button className={`theme-preview dark ${state.settings.appearance === 'dark' ? 'chosen' : ''}`} onClick={() => void mutate(s => { s.settings.appearance = 'dark' })}><div><i /><span><b /><b /><b /></span></div><strong>深色</strong></button></div><form onSubmit={async e => { const f = readForm(e); await mutate(s => { s.settings.timezone = str(f, 'timezone'); s.settings.notifications = f.has('notifications'); s.settings.startAtLogin = f.has('login') }) }}><TextField label="应用时区" name="timezone" value={state.settings.timezone} required hint="课程日期使用各自学期时区；此项用于手动事项、邮件总结与界面日期。" /><label className="check-label"><input type="checkbox" name="notifications" defaultChecked={state.settings.notifications} />启用桌面提醒</label><label className="check-label"><input type="checkbox" name="login" defaultChecked={state.settings.startAtLogin} />开机启动并驻留托盘（安装版生效）</label><p className="muted">关闭窗口后继续在托盘运行。选择托盘“退出”才会停止后台任务；电脑关机时无法总结或提醒。</p><div className="form-actions"><SaveButton label="保存桌面设置" /></div></form></section>
    <section className="surface settings-section"><div className="section-header"><h2>Gmail 连接</h2><Badge appearance="tint" color={connection?.email ? 'success' : 'subtle'}>{connection?.email ? '已连接' : '未连接'}</Badge></div><p className="muted">使用你自己的 Google Desktop OAuth 客户端，权限仅限读取邮件。</p>{connection?.email && <p className="info-note">{connection.email}</p>}{connection?.lastError && <p className="error-note">{connection.lastError}</p>}<form onSubmit={e => { const f = readForm(e); void run(async () => { setConnection(await window.workstation.saveSecrets({ clientId: str(f, 'clientId'), clientSecret: str(f, 'clientSecret') })) }, 'OAuth 配置已加密保存') }}><TextField label="Google OAuth 客户端 ID" name="clientId" placeholder={connection?.hasOAuth ? '已保存；留空保留原值' : '…apps.googleusercontent.com'} /><TextField label="Google OAuth 客户端密钥" name="clientSecret" type="password" placeholder="留空保留原值" hint="桌面应用客户端配置，由 Google Cloud 提供。" /><div className="form-actions"><SaveButton label="保存 OAuth 配置" /></div></form><div className="actions"><Button icon={<PlugConnected20Regular />} appearance="primary" disabled={busy || !connection?.hasOAuth} onClick={() => void run(async () => setConnection(await window.workstation.connectGmail()), 'Gmail 已连接')}>在浏览器中授权</Button>{connection?.email && <Button disabled={busy} onClick={() => void run(async () => { setConnection(await window.workstation.disconnectGmail()); await reload() }, '已断开，邮件与 AI 缓存已清除')}>断开 Gmail</Button>}</div><p className="muted">断开会清除本机邮件和 AI 缓存。可以在 Google 账号安全设置中撤销此应用的授权。</p><Button appearance="subtle" onClick={() => void run(() => window.workstation.openExternal('https://console.cloud.google.com/apis/credentials'))}>打开 Google Cloud 凭据页面</Button></section>
    <section className="surface settings-section"><div className="section-header"><h2>DeepSeek 助手</h2><Badge appearance="tint" color={connection?.hasKey ? 'success' : 'subtle'}>{connection?.hasKey ? 'Key 已保存' : '待配置'}</Badge></div><form onSubmit={e => { const f = readForm(e); const form = e.currentTarget; void run(async () => { setConnection(await window.workstation.saveSecrets({ apiKey: str(f, 'apiKey') })); form.reset() }, 'API key 已加密保存') }}><TextField label="API key" name="apiKey" type="password" placeholder="仅保存在此电脑，留空不修改" /><div className="form-actions"><Button disabled={busy || !connection?.hasKey} onClick={() => void run(async () => { await window.workstation.testAI() }, 'DeepSeek 连接测试成功')}>测试连接</Button><SaveButton label="保存 API key" /></div></form><form onSubmit={async e => { const f = readForm(e); await mutate(s => { s.settings.model = str(f, 'model'); s.settings.digestTime = str(f, 'time'); s.settings.digestEnabled = f.has('enabled') }) }}><TextField label="模型名称" name="model" value={state.settings.model} required /><TextField label="每日总结时间" name="time" value={state.settings.digestTime} type="time" required /><label className="check-label"><input type="checkbox" name="enabled" defaultChecked={state.settings.digestEnabled} />启用每日自动总结</label><div className="info-note">启用后，新增且仍在收件箱中的邮件正文（包含已读邮件）会发送到 DeepSeek，每日按应用时区总结。附件不参与。首次从启用时开始统计，错过时间后恢复运行补做。单封翻译会发送该封正文。</div><div className="form-actions"><SaveButton label="保存 AI 设置" /></div></form></section>
    <section className="surface settings-section"><h2>数据与备份</h2><p className="muted">学业与 TODO 保存于 Windows 用户应用数据目录。备份包含课程、考核、课表及偏好；凭据与邮件缓存不包含在备份中。</p><div className="backup-banner"><ShieldCheckmark20Regular /><div><strong>数据由你保管</strong><p>定期导出，在换电脑或重要修改前保留副本。</p></div></div><div className="actions"><Button icon={<ArrowDownload20Regular />} disabled={busy} onClick={() => void run(async () => { const path = await window.workstation.exportBackup(); if (!path) return }, '备份操作已结束')}>导出备份</Button><Button icon={<ArrowUpload20Regular />} disabled={busy} onClick={() => void run(async () => { await window.workstation.restoreBackup(); await reload() })}>恢复备份</Button></div><p className="muted">恢复前会预览备份内容并保存当前数据副本。恢复后默认关闭自动总结和开机启动。</p><div className="settings-about"><strong>Workstation</strong><span>0.1.0 · 本地个人版</span><Button appearance="subtle" onClick={() => void run(() => window.workstation.openExternal('https://github.com/alex-0v0-328/workstation'))}>项目与更新</Button></div></section></div>
  </>
}
