import { SemesterWizard } from './SemesterWizard'
import { useState, useEffect } from 'react'
import { Button, Badge } from '@fluentui/react-components'
import { Add20Regular, BookOpen32Regular, ArrowUpload20Regular, CalendarLtr20Regular, ArrowLeft20Regular, Edit20Regular } from '@fluentui/react-icons'
import type { Course, Semester, Hurdle } from '../../shared/types'
import { calculateGrade } from '../../shared/domain'
import { useModel, uid, statusLabel, formatDate } from './model'
import { Empty, SectionTitle, Panel, Field, TextField, SaveButton, readForm, str } from './components'
import { DateTime } from 'luxon'

export function StudyView() {
  const { state, setPage, editTask, run, reload, mutate } = useModel()
  const [semesterId, setSemesterId] = useState(''), [selected, setSelected] = useState(''), [wizard, setWizard] = useState(false), [courseEdit, setCourseEdit] = useState<Course | 'new' | null>(null), [hurdle, setHurdle] = useState<Hurdle | 'new' | null>(null), [archive, setArchive] = useState(false), [semEdit, setSemEdit] = useState(false)
  const semesters = state.semesters.filter(s => archive || !s.archived)
  const semester = semesters.find(s => s.id === semesterId) || semesters.at(-1)
  const courses = state.courses.filter(c => c.semesterId === semester?.id && (archive || !c.archived))
  const course = courses.find(c => c.id === selected)
  const assessments = state.assessments.filter(a => a.courseId === course?.id && !a.archived)
  const grade = calculateGrade(assessments)
  return <>
    <SectionTitle title="学习" subtitle="课程、考核与每周安排，保持清晰。" actions={<><Button icon={<ArrowUpload20Regular />} onClick={() => void run(async () => { await window.workstation.importAcademic(); await reload() })}>导入学业 JSON</Button><Button appearance="primary" icon={<Add20Regular />} onClick={() => setWizard(true)}>新建学期</Button></>} />
    <div className="study-toolbar"><select aria-label="当前学期" value={semester?.id || ''} onChange={e => { setSemesterId(e.target.value); setSelected('') }}>{!semesters.length && <option value="">尚无学期</option>}{semesters.map(s => <option key={s.id} value={s.id}>{s.name}{s.archived ? '（已归档）' : ''}</option>)}</select>{semester && <><span className="muted">{semester.start} — {semester.end}</span><Button appearance="subtle" icon={<Edit20Regular />} onClick={() => setSemEdit(true)}>学期设置</Button></>}<label className="check-label"><input type="checkbox" checked={archive} onChange={e => setArchive(e.target.checked)} />显示归档</label><Button appearance="subtle" icon={<CalendarLtr20Regular />} onClick={() => setPage('calendar')}>周课表</Button></div>
    {!semester ? <section className="surface"><Empty icon={<BookOpen32Regular />} title="开启一个新学期" action={() => setWizard(true)} actionLabel="填写学期信息">先确定学期日期，再逐步添加课程、考核与课表。所有信息都可以稍后补充。</Empty></section> : !course ? <>
      <div className="section-header"><h2>本学期课程 <span className="count">{courses.length}</span></h2><Button icon={<Add20Regular />} onClick={() => setCourseEdit('new')}>添加课程</Button></div>
      <div className="course-grid">{courses.map(c => {
        const items = state.assessments.filter(a => a.courseId === c.id && !a.archived), pending = items.filter(a => a.status !== 'done'), next = pending.filter(a => a.due || a.starts).sort((a, b) => (a.due || a.starts).localeCompare(b.due || b.starts))[0]
        return <button className="course-card surface" key={c.id} onClick={() => setSelected(c.id)}><div className="course-card-top"><span className="course-monogram" style={{ color: c.color, background: `${c.color}18` }}>{(c.code || c.name).slice(0, 2).toUpperCase()}</span><span>{c.code || '课程'}{c.archived ? ' · 已归档' : ''}</span></div><h2>{c.name}</h2><p>{pending.length} 项待完成 · {items.length} 个考核</p><div className="course-next">{next ? <><span>下一项</span><strong>{next.title}</strong><small>{formatDate(next.due || next.starts, semester.timezone)}</small></> : <><span>接下来的安排</span><strong>暂时没有已安排的考核</strong><small>进入课程添加或补充日期</small></>}</div></button>
      })}<button className="add-course" onClick={() => setCourseEdit('new')}><Add20Regular /><span>添加一门课程</span><small>支持任意课程体系</small></button></div>
    </> : <>
      <Button appearance="subtle" icon={<ArrowLeft20Regular />} onClick={() => setSelected('')}>所有课程</Button>
      <div className="course-detail-heading"><div><span className="eyebrow" style={{ color: course.color }}>{course.code || '课程'}</span><h2>{course.name}</h2><p>{course.notes || '在这里管理课程要求、考核与成绩。'}</p></div><div className="actions">{course.url && <Button onClick={() => void run(() => window.workstation.openExternal(course.url))}>课程主页</Button>}<Button onClick={() => setCourseEdit(course)}>编辑课程</Button><Button appearance="primary" icon={<Add20Regular />} onClick={() => editTask(undefined, course.id)}>添加考核</Button></div></div>
      <div className="grade-strip surface"><div><span>已获总评分</span><strong>{grade.earned.toFixed(1)}<small> / 100</small></strong></div><div><span>已评分权重</span><strong>{grade.gradedWeight.toFixed(1)}%</strong></div><div><span>未评分权重</span><strong>{grade.pendingWeight.toFixed(1)}%</strong></div><div><span>未分配权重</span><strong>{grade.unassignedWeight.toFixed(1)}%</strong></div></div>
      {!grade.complete && <p className="info-note">权重配置未完整或总和不是 100%（当前 {grade.assignedWeight}%）。已获分仅统计有数值成绩与权重的考核，不代表最终总评或 hurdle 通过。</p>}
      <section className="surface"><div className="section-header inset"><h3>考核安排</h3><span className="muted">进度会同步到 TODO</span></div>{assessments.length ? <div className="table-wrap"><table><thead><tr><th>考核</th><th>时间</th><th>权重</th><th>成绩</th><th>进度</th><th /></tr></thead><tbody>{assessments.map(a => <tr key={a.id}><td><strong>{a.title}</strong><small>{a.category}</small></td><td>{formatDate(a.due || a.starts, semester.timezone)}{a.opens && <small>开放：{formatDate(a.opens, semester.timezone)}</small>}</td><td>{a.weight === null ? '待定' : `${a.weight}%`}</td><td>{a.result || (a.score === null ? '未出分' : `${a.score} / ${a.maxScore}`)}</td><td><Badge appearance="tint" color={a.status === 'done' ? 'success' : 'subtle'}>{statusLabel[a.status]}</Badge></td><td><Button size="small" onClick={() => editTask(a)}>编辑</Button></td></tr>)}</tbody></table></div> : <Empty title="添加第一个考核" action={() => editTask(undefined, course.id)} actionLabel="添加考核">可以是 Assignment、MST、Final Exam，也可以自定义类别。</Empty>}</section>
      <section className="surface hurdle-section"><div className="section-header inset"><h3>Hurdle 要求</h3><Button icon={<Add20Regular />} onClick={() => setHurdle('new')}>添加要求</Button></div>{state.hurdles.filter(h => h.courseId === course.id).length ? state.hurdles.filter(h => h.courseId === course.id).map(h => <div className="hurdle-row" key={h.id}><div><strong>{h.text}</strong><small>{h.scope === 'course' ? '整门课程' : h.assessmentIds.map(i => state.assessments.find(a => a.id === i)?.title).join('、')}</small></div><Badge appearance="tint" color={h.status === 'met' ? 'success' : h.status === 'unmet' ? 'danger' : 'subtle'}>{({ pending: '待确认', met: '已满足', unmet: '未满足' })[h.status]}</Badge><Button size="small" onClick={() => setHurdle(h)}>编辑</Button></div>) : <p className="inset muted">暂无 hurdle 要求。只有课程明确规定时才添加。</p>}</section>
    </>}
    {wizard && <SemesterWizard close={() => setWizard(false)} finish={id => { setSemesterId(id); setSelected('') }} />}
    {courseEdit && semester && <CourseEditor semesterId={semester.id} course={courseEdit === 'new' ? undefined : courseEdit} close={() => setCourseEdit(null)} />}
    {hurdle && course && <HurdleEditor courseId={course.id} item={hurdle === 'new' ? undefined : hurdle} close={() => setHurdle(null)} />}
    {semEdit && semester && <Panel title="学期设置" close={() => setSemEdit(false)}><form onSubmit={async e => { const f = readForm(e); if (await mutate(s => { const target = s.semesters.find(x => x.id === semester.id)!; Object.assign(target, { name: str(f, 'name'), start: str(f, 'start'), end: str(f, 'end'), timezone: str(f, 'timezone'), weekStart: str(f, 'weekStart'), holidays: str(f, 'holidays') }) })) setSemEdit(false) }}><TextField label="名称" name="name" value={semester.name} required /><div className="form-grid"><TextField label="开始日期" name="start" value={semester.start} type="date" required /><TextField label="结束日期" name="end" value={semester.end} type="date" required /></div><TextField label="时区" name="timezone" value={semester.timezone} required /><TextField label="教学第一周起点" name="weekStart" value={semester.weekStart} type="date" /><TextField label="假期 / 停课说明" name="holidays" value={semester.holidays} hint="保留原始说明；手动课表中的例外日期可排除具体停课日。" /><div className="form-actions"><Button onClick={async () => { if (await mutate(s => { s.semesters.find(x => x.id === semester.id)!.archived = !semester.archived })) setSemEdit(false) }}>{semester.archived ? '取消归档' : '归档学期'}</Button><SaveButton /></div></form></Panel>}
  </>
}

function CourseEditor({ semesterId, course, close }: { semesterId: string; course?: Course; close(): void }) {
  const { mutate } = useModel()
  return <Panel title={course ? '编辑课程' : '添加课程'} close={close}><form onSubmit={async e => { const f = readForm(e); const next: Course = { id: course?.id || uid(), semesterId, name: str(f, 'name'), code: str(f, 'code'), color: str(f, 'color'), url: str(f, 'url'), notes: str(f, 'notes'), archived: course?.archived || false }; if (await mutate(s => { const index = s.courses.findIndex(c => c.id === next.id); if (index < 0) s.courses.push(next); else s.courses[index] = next })) close() }}><TextField label="课程名称" name="name" value={course?.name} required /><div className="form-grid"><TextField label="课程代码" name="code" value={course?.code} /><TextField label="颜色" name="color" type="color" value={course?.color || '#0078d4'} /></div><TextField label="课程主页 / LMS 链接" name="url" value={course?.url} type="url" /><Field label="备注"><textarea name="notes" defaultValue={course?.notes} rows={3} /></Field><div className="form-actions">{course && <Button onClick={async () => { if (await mutate(s => { s.courses.find(x => x.id === course.id)!.archived = !course.archived })) close() }}>{course.archived ? '取消归档' : '归档课程'}</Button>}<SaveButton /></div></form></Panel>
}
export function HurdleEditor({ courseId, item, close }: { courseId: string; item?: Hurdle; close(): void }) {
  const { state, mutate } = useModel()
  const [scope, setScope] = useState<Hurdle['scope']>(item?.scope || 'course')
  return <Panel title="Hurdle 要求" close={close}><form onSubmit={async e => { const f = readForm(e); const next: Hurdle = { id: item?.id || uid(), courseId, text: str(f, 'text'), scope, assessmentIds: scope === 'course' ? [] : f.getAll('assessments').map(String), status: str(f, 'status') as Hurdle['status'] }; if (await mutate(s => { const index = s.hurdles.findIndex(h => h.id === next.id); if (index < 0) s.hurdles.push(next); else s.hurdles[index] = next })) close() }}><Field label="要求原文"><textarea name="text" defaultValue={item?.text} required rows={4} /></Field><Field label="适用范围"><select value={scope} onChange={e => setScope(e.target.value as Hurdle['scope'])}><option value="course">整门课程</option><option value="assessment">指定一个考核</option><option value="group">一组考核</option></select></Field>{scope !== 'course' && <Field label="关联考核（按住 Ctrl 多选）"><select multiple name="assessments" defaultValue={item?.assessmentIds || []}>{state.assessments.filter(a => a.courseId === courseId).map(a => <option key={a.id} value={a.id}>{a.title}</option>)}</select></Field>}<Field label="人工确认状态"><select name="status" defaultValue={item?.status || 'pending'}><option value="pending">待确认</option><option value="met">已满足</option><option value="unmet">未满足</option></select></Field><p className="muted">根据课程要求和已知结果手动确认，不自动推断复杂组合规则。</p><div className="form-actions"><SaveButton /></div></form></Panel>
}
