import { SemesterWizard } from './SemesterWizard'
import { useState, type CSSProperties } from 'react'
import { Button } from '@fluentui/react-components'
import { DateTime } from 'luxon'
import { Add20Regular, BookOpen32Regular, ArrowUpload20Regular, CalendarLtr20Regular, ArrowLeft20Regular, Edit20Regular } from '@fluentui/react-icons'
import type { Course, Semester, Hurdle } from '../../shared/types'
import { calculateGrade } from '../../shared/domain'
import { semesterWeeks } from '../../shared/calendar'
import { StepKeys } from './StepRow'
import { useModel, uid, formatDate } from './model'
import { Empty, SectionTitle, Panel, Field, TextField, SaveButton, readForm, str } from './components'

export function StudyView() {
  const { state, setPage, editTask, run, reload, mutate, messages, t } = useModel()
  const [semesterId, setSemesterId] = useState(''), [selected, setSelected] = useState(''), [wizard, setWizard] = useState(false), [courseEdit, setCourseEdit] = useState<Course | 'new' | null>(null), [hurdle, setHurdle] = useState<Hurdle | 'new' | null>(null), [archive, setArchive] = useState(false), [semEdit, setSemEdit] = useState(false)
  const semesters = state.semesters.filter(s => archive || !s.archived)
  const semester = semesters.find(s => s.id === semesterId) || semesters.at(-1)
  const courses = state.courses.filter(c => c.semesterId === semester?.id && (archive || !c.archived))
  const course = courses.find(c => c.id === selected)
  const assessments = state.assessments.filter(a => a.courseId === course?.id && !a.archived)
  const grade = calculateGrade(assessments)
  const now = DateTime.now()
  const weeks = semester ? semesterWeeks(semester, [], now) : []
  return <>
    <SectionTitle title={t('study.heading')} actions={<><Button icon={<ArrowUpload20Regular />} onClick={() => void run(async () => { await window.workstation.importAcademic(); await reload() })}>{t('study.import')}</Button><Button appearance="primary" icon={<Add20Regular />} onClick={() => setWizard(true)}>{t('study.newSemester')}</Button></>} />
    <div className="study-toolbar"><select aria-label={t('study.semesterAria')} value={semester?.id || ''} onChange={e => { setSemesterId(e.target.value); setSelected('') }}>{!semesters.length && <option value="">{t('study.noSemester')}</option>}{semesters.map(s => <option key={s.id} value={s.id}>{s.name}{s.archived ? t('study.archivedTag') : ''}</option>)}</select>{semester && <><span className="muted">{semester.start} — {semester.end}</span><Button appearance="subtle" icon={<Edit20Regular />} onClick={() => setSemEdit(true)}>{t('study.semesterSettings')}</Button></>}<label className="check-label"><input type="checkbox" checked={archive} onChange={e => setArchive(e.target.checked)} />{t('study.showArchived')}</label><Button appearance="subtle" icon={<CalendarLtr20Regular />} onClick={() => setPage('calendar')}>{t('nav.calendar')}</Button></div>
    {!semester ? <section className="surface"><Empty icon={<BookOpen32Regular />} title={t('study.emptySemesterTitle')} action={() => setWizard(true)} actionLabel={t('study.emptySemesterAction')}>{t('study.emptySemesterBody')}</Empty></section> : !course ? <>
      <section className="surface sequencer"><div className="panel-head"><span className="label">{t('study.coursesHeading')}<span className="count">{courses.length}</span></span><Button icon={<Add20Regular />} onClick={() => setCourseEdit('new')}>{t('study.addCourse')}</Button></div>
        <div className="seq-grid"><div className="seq-head label">{t('study.seqCourse')}</div><div className="seq-head"><div className="seq-weeks" aria-hidden="true">{weeks.map(w => <span key={w.index} className={w.now ? 'now' : ''}>{w.index}</span>)}</div></div><div className="seq-head seq-next-head label">{t('study.nextLabel')}</div>
          {courses.map(c => {
            const items = state.assessments.filter(a => a.courseId === c.id && !a.archived), pending = items.filter(a => a.status !== 'done'), next = pending.filter(a => a.due || a.starts).sort((a, b) => (a.due || a.starts).localeCompare(b.due || b.starts))[0]
            return <div className="seq-row" key={c.id}><button className="seq-course" onClick={() => setSelected(c.id)}><span className="channel" style={{ '--channel': c.color } as CSSProperties}>{c.code || t('study.courseFallback')}{c.archived ? t('study.archivedSuffix') : ''}</span><strong>{c.name}</strong><small>{t('study.courseStats', { pending: pending.length, total: items.length })}</small></button><div className="seq-steps"><StepKeys weeks={semesterWeeks(semester, items, now)} /></div><div className="seq-next">{next ? <><strong>{next.title}</strong><small>{formatDate(messages, next.due || next.starts, semester.timezone)}</small></> : <small>{t('study.nextEmptyTitle')}</small>}</div></div>
          })}
        </div>
        <button className="seq-add" onClick={() => setCourseEdit('new')}><Add20Regular />{t('study.addCourseTile')}</button>
      </section>
    </> : <>
      <Button appearance="subtle" icon={<ArrowLeft20Regular />} onClick={() => setSelected('')}>{t('study.backToCourses')}</Button>
      <div className="course-detail-heading"><div><h2>{course.name}</h2><p><span className="channel" style={{ '--channel': course.color } as CSSProperties}>{course.code || t('study.courseFallback')}</span> {course.notes || t('study.courseNotesFallback')}</p></div><div className="actions">{course.url && <Button onClick={() => void run(() => window.workstation.openExternal(course.url))}>{t('study.courseHome')}</Button>}<Button onClick={() => setCourseEdit(course)}>{t('study.editCourse')}</Button><Button appearance="primary" icon={<Add20Regular />} onClick={() => editTask(undefined, course.id)}>{t('study.addAssessment')}</Button></div></div>
      <div className="grade-readouts surface"><div className="readouts"><div className="readout"><span className="label">{t('study.gradeEarned')}</span><strong className="readout-value">{grade.earned.toFixed(1)}<small>/ 100</small></strong></div><div className="readout"><span className="label">{t('study.gradedWeight')}</span><strong className="readout-value">{grade.gradedWeight.toFixed(1)}<small>%</small></strong></div><div className="readout"><span className="label">{t('study.pendingWeight')}</span><strong className="readout-value">{grade.pendingWeight.toFixed(1)}<small>%</small></strong></div><div className="readout"><span className="label">{t('study.unassignedWeight')}</span><strong className="readout-value">{grade.unassignedWeight.toFixed(1)}<small>%</small></strong></div></div></div>
      {!grade.complete && <p className="info-note">{t('study.gradeIncomplete', { weight: grade.assignedWeight })}</p>}
      <section className="surface"><div className="panel-head"><span className="label">{t('study.assessmentsHeading')}</span><span className="muted">{t('study.assessmentsSync')}</span></div>{assessments.length ? <div className="table-wrap"><table><thead><tr><th>{t('study.thAssessment')}</th><th>{t('study.thTime')}</th><th>{t('study.thWeight')}</th><th>{t('study.thGrade')}</th><th>{t('study.thProgress')}</th><th /></tr></thead><tbody>{assessments.map(a => <tr key={a.id}><td><strong>{a.title}</strong><small>{a.category}</small></td><td>{formatDate(messages, a.due || a.starts, semester.timezone)}{a.opens && <small>{t('study.opensAt', { date: formatDate(messages, a.opens, semester.timezone) })}</small>}</td><td>{a.weight === null ? t('study.weightTbd') : `${a.weight}%`}</td><td>{a.result || (a.score === null ? t('study.noScore') : `${a.score} / ${a.maxScore}`)}</td><td><span className="state-mark"><i className={`led ${a.status === 'done' ? 'ok' : a.status === 'doing' ? 'on' : ''}`} />{messages.status[a.status]}</span></td><td><Button size="small" onClick={() => editTask(a)}>{t('common.edit')}</Button></td></tr>)}</tbody></table></div> : <Empty title={t('study.emptyAssessmentsTitle')} action={() => editTask(undefined, course.id)} actionLabel={t('study.addAssessment')}>{t('study.emptyAssessmentsBody')}</Empty>}</section>
      <section className="surface hurdle-section"><div className="panel-head"><span className="label">{t('study.hurdleHeading')}</span><Button icon={<Add20Regular />} onClick={() => setHurdle('new')}>{t('study.addHurdle')}</Button></div>{state.hurdles.filter(h => h.courseId === course.id).length ? state.hurdles.filter(h => h.courseId === course.id).map(h => <div className="hurdle-row" key={h.id}><div><strong>{h.text}</strong><small>{h.scope === 'course' ? t('study.hurdleCourseScope') : h.assessmentIds.map(i => state.assessments.find(a => a.id === i)?.title).join('、')}</small></div><span className="state-mark"><i className={`led ${h.status === 'met' ? 'ok' : h.status === 'unmet' ? 'warn' : ''}`} />{messages.study.hurdleStatus[h.status]}</span><Button size="small" onClick={() => setHurdle(h)}>{t('common.edit')}</Button></div>) : <p className="inset muted">{t('study.hurdleEmpty')}</p>}</section>
    </>}
    {wizard && <SemesterWizard close={() => setWizard(false)} finish={id => { setSemesterId(id); setSelected('') }} />}
    {courseEdit && semester && <CourseEditor semesterId={semester.id} course={courseEdit === 'new' ? undefined : courseEdit} close={() => setCourseEdit(null)} />}
    {hurdle && course && <HurdleEditor courseId={course.id} item={hurdle === 'new' ? undefined : hurdle} close={() => setHurdle(null)} />}
    {semEdit && semester && <Panel title={t('study.semesterSettings')} close={() => setSemEdit(false)}><form onSubmit={async e => { const f = readForm(e); if (await mutate(s => { const target = s.semesters.find(x => x.id === semester.id)!; Object.assign(target, { name: str(f, 'name'), start: str(f, 'start'), end: str(f, 'end'), timezone: str(f, 'timezone'), weekStart: str(f, 'weekStart'), holidays: str(f, 'holidays') }) })) setSemEdit(false) }}><TextField label={t('study.fieldName')} name="name" value={semester.name} required /><div className="form-grid"><TextField label={t('study.fieldStart')} name="start" value={semester.start} type="date" required /><TextField label={t('study.fieldEnd')} name="end" value={semester.end} type="date" required /></div><TextField label={t('study.fieldTimezone')} name="timezone" value={semester.timezone} required /><TextField label={t('study.fieldWeekStart')} name="weekStart" value={semester.weekStart} type="date" /><TextField label={t('study.fieldHolidays')} name="holidays" value={semester.holidays} hint={t('study.fieldHolidaysHint')} /><div className="form-actions"><Button onClick={async () => { if (await mutate(s => { s.semesters.find(x => x.id === semester.id)!.archived = !semester.archived })) setSemEdit(false) }}>{semester.archived ? t('common.unarchive') : t('study.archiveSemester')}</Button><SaveButton /></div></form></Panel>}
  </>
}

function CourseEditor({ semesterId, course, close }: { semesterId: string; course?: Course; close(): void }) {
  const { mutate, t } = useModel()
  return <Panel title={course ? t('study.editCourseTitle') : t('study.addCourseTitle')} close={close}><form onSubmit={async e => { const f = readForm(e); const next: Course = { id: course?.id || uid(), semesterId, name: str(f, 'name'), code: str(f, 'code'), color: str(f, 'color'), url: str(f, 'url'), notes: str(f, 'notes'), archived: course?.archived || false }; if (await mutate(s => { const index = s.courses.findIndex(c => c.id === next.id); if (index < 0) s.courses.push(next); else s.courses[index] = next })) close() }}><TextField label={t('study.courseName')} name="name" value={course?.name} required /><div className="form-grid"><TextField label={t('study.courseCode')} name="code" value={course?.code} /><TextField label={t('study.courseColor')} name="color" type="color" value={course?.color || '#0078d4'} /></div><TextField label={t('study.courseUrl')} name="url" value={course?.url} type="url" /><Field label={t('study.courseNotes')}><textarea name="notes" defaultValue={course?.notes} rows={3} /></Field><div className="form-actions">{course && <Button onClick={async () => { if (await mutate(s => { s.courses.find(x => x.id === course.id)!.archived = !course.archived })) close() }}>{course.archived ? t('common.unarchive') : t('study.archiveCourse')}</Button>}<SaveButton /></div></form></Panel>
}
export function HurdleEditor({ courseId, item, close }: { courseId: string; item?: Hurdle; close(): void }) {
  const { state, mutate, messages, t } = useModel()
  const [scope, setScope] = useState<Hurdle['scope']>(item?.scope || 'course')
  return <Panel title={t('study.hurdleHeading')} close={close}><form onSubmit={async e => { const f = readForm(e); const next: Hurdle = { id: item?.id || uid(), courseId, text: str(f, 'text'), scope, assessmentIds: scope === 'course' ? [] : f.getAll('assessments').map(String), status: str(f, 'status') as Hurdle['status'] }; if (await mutate(s => { const index = s.hurdles.findIndex(h => h.id === next.id); if (index < 0) s.hurdles.push(next); else s.hurdles[index] = next })) close() }}><Field label={t('study.hurdleText')}><textarea name="text" defaultValue={item?.text} required rows={4} /></Field><Field label={t('study.hurdleScope')}><select value={scope} onChange={e => setScope(e.target.value as Hurdle['scope'])}><option value="course">{t('study.hurdleScopeCourse')}</option><option value="assessment">{t('study.hurdleScopeSingle')}</option><option value="group">{t('study.hurdleScopeGroup')}</option></select></Field>{scope !== 'course' && <Field label={t('study.hurdleLinked')}><select multiple name="assessments" defaultValue={item?.assessmentIds || []}>{state.assessments.filter(a => a.courseId === courseId).map(a => <option key={a.id} value={a.id}>{a.title}</option>)}</select></Field>}<Field label={t('study.hurdleStatusLabel')}><select name="status" defaultValue={item?.status || 'pending'}><option value="pending">{messages.study.hurdleStatus.pending}</option><option value="met">{messages.study.hurdleStatus.met}</option><option value="unmet">{messages.study.hurdleStatus.unmet}</option></select></Field><p className="muted">{t('study.hurdleNote')}</p><div className="form-actions"><SaveButton /></div></form></Panel>
}
