const { _electron: electron } = require('playwright')
const { mkdirSync, readFileSync, writeFileSync, readdirSync } = require('node:fs')
const path = require('node:path')
const assert = require('node:assert/strict')

async function main() {
  const folder = path.resolve('.local', `smoke-${Date.now()}`)
  mkdirSync(folder, { recursive: true })
  const launch = { ...(process.env.WORKSTATION_PACKAGED ? { executablePath: path.resolve(process.env.WORKSTATION_PACKAGED), args: ['--hidden'] } : { args: ['.', '--hidden'] }), env: { ...process.env, WORKSTATION_TEST_DATA: folder }, timeout: 30000 }
  const instance = await electron.launch(launch)
  instance.process().stderr.on('data', d => { const text = String(d); if (!text.includes('cache_util_win') && !text.includes('gpu_disk_cache')) process.stderr.write(text) })
  try {
    const page = await instance.firstWindow()
    await instance.evaluate(({ BrowserWindow }) => { for (const window of BrowserWindow.getAllWindows()) window.webContents.setBackgroundThrottling(false) })
    page.setDefaultTimeout(15000)
    const errors = []
    page.on('pageerror', e => errors.push(e.message))
    await page.getByRole('heading', { name: '今天，专注重要的事' }).waitFor()
    await page.screenshot({ path: path.join(folder, '01-empty.png') })
    console.log('STARTUP_OK', await page.title())
    await page.getByRole('button', { name: '添加事项', exact: true }).first().click()
    await page.locator('input[name="title"]').fill('Smoke test: plan the week')
    await page.locator('input[name="due"]').fill('2026-09-14')
    await page.getByRole('button', { name: '保存', exact: true }).click()
    await page.getByRole('dialog').waitFor({ state: 'hidden' })
    assert.notEqual(await page.locator('#root').getAttribute('aria-hidden'), 'true')
    await page.getByRole('tab', { name: '全部', exact: true }).click()
    await page.getByRole('button', { name: /Smoke test: plan the week/ }).waitFor()
    await page.getByRole('button', { name: '学习', exact: true }).click()
    await page.getByRole('button', { name: '新建学期', exact: true }).click()
    await page.getByLabel('学期名称', { exact: true }).fill('Demo Semester 2026')
    await page.getByLabel('开始日期', { exact: true }).fill('2026-07-20')
    await page.getByLabel('结束日期', { exact: true }).fill('2026-11-30')
    await page.getByLabel('本学期课程数量', { exact: true }).fill('2')
    await page.getByRole('button', { name: '下一步', exact: true }).click()
    await page.getByLabel('课程 1 名称', { exact: true }).fill('Interaction Design')
    await page.getByLabel('课程 2 名称', { exact: true }).fill('Applied Mathematics')
    await page.getByRole('button', { name: '下一步', exact: true }).click()
    await page.getByRole('dialog', { name: '建立新学期' }).getByRole('button', { name: '添加考核', exact: true }).first().click()
    await page.locator('input[name="title"]').fill('MST date pending')
    await page.getByRole('button', { name: '保存', exact: true }).click()
    await page.getByRole('dialog', { name: '添加考核', exact: true }).waitFor({ state: 'hidden' })
    await page.getByRole('button', { name: '下一步', exact: true }).click()
    await page.getByRole('button', { name: '下一步', exact: true }).click()
    await page.getByRole('button', { name: '确认创建学期', exact: true }).click()
    await page.getByRole('dialog').waitFor({ state: 'hidden' })
    await page.getByRole('button', { name: /Interaction Design.*1 项待完成/ }).click()
    await page.getByRole('button', { name: '添加考核', exact: true }).first().click()
    await page.locator('input[name="title"]').fill('Research assignment')
    await page.locator('input[name="due"]').fill('2026-09-20')
    await page.locator('input[name="weight"]').fill('30')
    await page.locator('input[name="score"]').fill('0')
    await page.locator('input[name="maxScore"]').fill('100')
    await page.getByRole('button', { name: '保存', exact: true }).click()
    await page.getByRole('dialog').waitFor({ state: 'hidden' })
    await page.getByRole('cell', { name: 'Research assignment Assignment' }).waitFor()
    let state = await page.evaluate(() => window.workstation.load())
    assert.equal(state.assessments.find(a => a.title === 'Research assignment').score, 0)
    assert.equal(state.tasks.length, 1)
    await page.screenshot({ path: path.join(folder, '02-study.png') })
    await page.getByRole('button', { name: /^TODO/ }).click()
    await page.getByRole('tab', { name: '全部', exact: true }).click()
    await page.getByRole('checkbox', { name: '完成 Research assignment' }).click()
    await page.getByRole('tab', { name: '已完成', exact: true }).click()
    await page.getByRole('button', { name: /Research assignment/ }).waitFor()
    state = await page.evaluate(() => window.workstation.load())
    assert.equal(state.assessments.find(a => a.title === 'Research assignment').status, 'done')
    assert.equal(state.tasks.length, 1)
    await page.getByRole('button', { name: '设置', exact: true }).click()
    await page.getByRole('button', { name: '深色', exact: true }).click()
    await page.locator('.dark-mode').waitFor()
    await page.evaluate(() => new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve))))
    console.log('DARK_TOKEN', await page.locator('.root-theme').evaluate(el => getComputedStyle(el).getPropertyValue('--colorNeutralBackground1')))
    await page.screenshot({ path: path.join(folder, '03-dark.png') })
    const themeFile = path.resolve(__dirname, '..', 'themes', 'dist', 'catppuccin.wstheme.json')
    await instance.evaluate(({ dialog }, file) => {
      dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [file] })
    }, themeFile)
    await page.getByRole('button', { name: '安装主题', exact: true }).click()
    await page.getByRole('button', { name: 'Catppuccin', exact: true }).click()
    await page.locator('.theme-catppuccin').waitFor()
    await page.getByRole('button', { name: 'Macchiato', exact: true }).click()
    await page.locator('.theme-catppuccin.variant-macchiato').waitFor()
    await page.screenshot({ path: path.join(folder, '03b-catppuccin.png') })
    state = await page.evaluate(() => window.workstation.load())
    assert.equal(state.tasks.length, 1)
    await page.getByRole('button', { name: '安装', exact: true }).click()
    await page.getByRole('button', { name: '复古 Windows', exact: true }).click()
    await page.locator('.theme-retro.shell-taskbar').waitFor()
    await page.screenshot({ path: path.join(folder, '03c-retro.png') })
    await page.getByRole('button', { name: 'Windows 11', exact: true }).click()
    await page.locator('.theme-windows.dark-mode').waitFor()
    state = await page.evaluate(() => window.workstation.load())
    assert.equal(state.tasks.length, 1)
    assert.equal(state.semesters.length, 1)
    assert.equal(await page.locator('#root').getAttribute('aria-hidden'), null)
    console.log('THEMES_OK')
    await page.getByRole('button', { name: '周课表', exact: true }).click()
    await page.getByRole('button', { name: '手动安排', exact: true }).click()
    await page.locator('input[name="title"]').fill('Weekly lecture')
    await page.getByRole('button', { name: '生成课程安排', exact: true }).click()
    await page.getByRole('dialog').waitFor({ state: 'hidden' })
    state = await page.evaluate(() => window.workstation.load())
    assert(state.events.length > 10)
    await page.screenshot({ path: path.join(folder, '04-calendar.png') })
    await page.getByRole('button', { name: '生活', exact: true }).click()
    await page.getByRole('heading', { name: '连接你的 Gmail', exact: true }).waitFor()
    const backupFile = path.join(folder, 'backup-test.json')
    await instance.evaluate(({ dialog }, file) => {
      dialog.showSaveDialog = async () => ({ canceled: false, filePath: file })
      dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [file] })
      dialog.showMessageBox = async () => ({ response: 1, checkboxChecked: false })
    }, backupFile)
    await page.evaluate(() => window.workstation.exportBackup())
    const backup = JSON.parse(readFileSync(backupFile, 'utf8'))
    assert.equal(backup.settings.digestEnabled, false)
    assert.equal(JSON.stringify(backup).includes('apiKey'), false)
    await page.evaluate(async () => { const s = await window.workstation.load(); s.tasks[0].title = 'Changed after backup'; await window.workstation.save(s) })
    await page.evaluate(() => window.workstation.restoreBackup())
    const restored = await page.evaluate(() => window.workstation.load())
    assert.equal(restored.tasks[0].title, 'Smoke test: plan the week')
    assert(readdirSync(folder).some(file => file.startsWith('before-restore-')))
    writeFileSync(backupFile, JSON.stringify({ version: 99 }))
    const invalid = await page.evaluate(async () => { try { await window.workstation.restoreBackup(); return false } catch { return true } })
    assert.equal(invalid, true)
    assert.equal((await page.evaluate(() => window.workstation.load())).tasks[0].title, 'Smoke test: plan the week')
    console.log('BACKUP_RESTORE_OK')
    await page.setViewportSize({ width: 1000, height: 760 })
    await page.getByRole('button', { name: 'TODO', exact: false }).first().click()
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth), false)
    await page.screenshot({ path: path.join(folder, '05-narrow.png') })
    assert.deepEqual(errors, [])
    console.log('SMOKE_OK', JSON.stringify({ semesters: state.semesters.length, courses: state.courses.length, assessments: state.assessments.length, tasks: state.tasks.length, events: state.events.length, screenshotFolder: folder }))
    await instance.close()
    const reopened = await electron.launch(launch)
    try { const secondPage = await reopened.firstWindow(); await secondPage.getByRole('heading', { name: '今天，专注重要的事' }).waitFor(); const persisted = await secondPage.evaluate(() => window.workstation.load()); assert.equal(persisted.assessments.find(a => a.title === 'Research assignment').status, 'done'); assert.equal(persisted.settings.appearance, 'dark'); console.log('PERSISTENCE_OK') } finally { await reopened.close() }
  } catch (e) {
    const page = (await instance.windows())[0]
    console.error('SMOKE_FAILURE', e)
    if (page) { console.log((await page.locator('body').innerText()).slice(0, 7000)); await page.screenshot({ path: path.join(folder, 'failure.png'), timeout: 5000 }).catch(() => {}) }
    throw e
  } finally { await instance.close().catch(() => {}) }
}
main().catch(e => { console.error(e); process.exitCode = 1 })
